#!/usr/bin/env bash

# don't even thing about scripting a make clean for C-M

cd /Users/kfl/dev/git/Cartoon-Mobile/AndroidBuild
make android-app

cd /Users/kfl/dev/git/piano-core
make local-install

# clear all data
adb shell rm sdcard/pianocore_experimental_db_micro
