#!/usr/bin/env bash

# don't even thing about scripting a make clean for C-M

#cd /Users/kfl/dev/git/private_projects/Cartoon-Mobile/AndroidBuild
#make android-app

# cd /Users/kfl/dev/git/private_projects/piano-core
# make local-install

# clear all data
adb shell rm sdcard/pianocore_experimental_db_micro
